package com.patron

object BannedList {
    val filtrelenenler: List<String> = listOf(
        "Desire", "40 Made ni Shitai 10 no Koto", "Ameagari no Bokura ni Tsuite", "A Sketchy Job",
        "Missing You", "The Promise of the Soul", "Wrong Number", "Sotus", "7 Times 4 Days", "Shine",
        "Revenged Love", "Boys Vibe The Project", "Suntiny", "Hishakai Shindo",
        "I Became the Lead in a BL Drama", "Love Upon a Time", "Goddess Bless You from Death",
        "Dare You to Death", "Cat for Cash", "Memoir of Rati", "Ball Boy Tactics", "You(r)Tuber",
        "Interminable", "Love You Teacher", "Trapped in Osaka", "My Sweet Brother in Law",
        "The Sparkle In Your Eye", "Moon and Dust", "Infidelity", "It's a Disease",
        "I Promise I Will Come Back", "Loy Kaew First Love", "I'm the Most Beautiful Count",
        "Vice Versa", "Lovely Writer", "Season of Love in Shimane", "A Dog and a Plane",
        "My Magic Prophecy", "Reset", "Theory of Love", "The Ex-Morning", "Eye Contact", "Me and Thee",
        "Burnout Syndrome", "Ticket to Heaven", "Khemjira", "Sweetheart Service", "Mission to the Moon",
        "Never Fair", "Secrets Happened on the Litchi Island", "The Bangkok Boy", "Knock Out",
        "My Sweetheart Jom", "Love Casting", "La Pluie", "My Stubborn", "Secret Ghost",
        "My Tooth Your Love", "Chains of Heart", "Something Is Not Right", "Boys in Love",
        "The Racing Track", "Business as Usual", "Heesu in Class 2", "Fight for You",
        "The Tasty Florida", "Lost in the Woods", "Sweet Tooth", "Good Dentist", "Close To You",
        "Fish Upon the Sky", "Last Twilight in Phuket", "Dark Blue Kiss", "The Miracle of Teddy Bear",
        "The Eclipse", "Why R U?", "Last Meal Universe", "Secret Relationships", "My Golden Blood",
        "A Perfect Match", "PorschArm the Wedding", "The Last Time", "Backlight", "Sweet Curse",
        "Fight for Love", "Heart Stain", "Great Men Academy", "The Renovation", "Checkered Shirt",
        "Top Form", "Gelboys", "Never Let Me Go", "Flirt Milk", "FC Soldout", "Silent Sparks",
        "Exclusive Love", "HIStory4: Close to You", "My School President", "Impression of Youth",
        "The Paradise of Thorns", "I'll Turn Back This Time", "Bad to Bed",
        "When It Rains, It Pours", "Laws of Attraction", "The Boy Next World",
        "The Shorthest Distance is Round - Rain and Soda +21",
        "The Shortest Distance is Round - Blanc +21", "Only for Fans", "Sangmin Dinneaw",
        "The Shortest Distance - Fallen Flowers +18", "Summerdaze", "Manner of Death",
        "The Novelist - Continued Spring Life", "Eternal Butler", "That's My Candy",
        "Bridge of Destiny", "Goodbye Mother", "The Novelist", "Bad Buddy", "Ossan's Love",
        "Innocent", "Capture Lover", "Craving You", "Love in the Big City", "Oh! My Assistant",
        "HIStory1", "I Feel You Linger in the Air", "Mood Indigo", "0.5D", "Spare Me Your Mercy",
        "ThamePo Heart That Skips a Beat", "Winter Is Not the Death of Summer but the Birth of Spring",
        "Let Me Hear It Barefoot", "Triage", "Stay with Me", "Method", "Love by Chance",
        "The Nipple Talk", "A Balloon's Landing", "Secret Love (TH)", "Caged Again", "Our Youth",
        "The Middleman's Love", "Stay by My Side", "The Heart Killers", "More than Words",
        "Love in the Air: Koi no Yokan", "Perfect 10 Liners", "Make Up", "Make Me Grow Up!",
        "Love in Translation", "Dear Doctor, I'm Coming for Soul", "HIStory3: Trapped",
        "See Your Love", "I Promised You the Moon", "I Told Sunset about You",
        "The Shortest Distance Is Round: Noir / +21", "The End of the World",
        "Let Free the Curse of Taekwondo", "Polyethylene Terephthalate", "Heavens x Candy +21",
        "Eccentric Romance", "Every You, Every Me", "Love Mechanics", "My Damn Business",
        "Uncle Unknown", "Fourever You", "Teenager Judge", "Ghost Host Ghost House", "Still 2gether",
        "The Cornered Mouse Dreams of Cheese", "Original Sin", "Moonlight Chicken", "2gether",
        "KinnPorsche", "A Tale of Thousand Stars", "Domestic Incident", "HIStory2: Crossing the Line",
        "Smells Like Green Spirit", "Doku Koi: Doku mo Sugireba Koi to Naru", "Bad Guy My Boss",
        "Eternal Yesterday", "Love Sick", "The Time of Fever", "Jack & Joker: U Steal My Heart!",
        "PD", "Plus & Minus", "The Sign", "Love Bill", "I Cannot Reach You", "Happy of the End",
        "The Hidden Moon", "Live in Love", "We Best Love", "Because of You", "Jack o' Frost",
        "Between Us", "Kidnap", "Memory in the Letter", "Until We Meet Again", "The On1y One",
        "Seoul Blues", "Ossan's Love: LOVE or DEAD", "Only Boo!", "Monster Next Door",
        "First Note of Love", "Addicted Heroin", "Silhouette of Your Voice",
        "Blue Canvas of Youthful Days", "Oxygen", "Battle of the Writers",
        "Be Loved in House: I Do", "Don't Say No", "Cosmetic Playlover", "Sugar Dog Life",
        "My Bromance", "Bad Guy", "HI Story 2: Right or Wrong", "Remember Me", "Love in the Air",
        "Kiseki: Dear to Me", "Candy Color Paradox", "Oh! Boarding House", "Not Me", "Once Again",
        "Kamisama no Ekohiiki", "4 Minutes", "I Saw You in My Dream", "Where Your Eyes Linger",
        "My Beautiful Man: Eternal", "Utsukushii Kare", "One Room Angel", "The Boyfriend",
        "8.2 Byo no Hosoku", "Hold", "Mr. Unlucky Has No Choice but to Kiss!",
        "Takara-kun to Amagi-kun", "A Distant Place", "Meet You at the Blossom", "Century of Love",
        "This Love Doesn't Have Long Beans", "Takara no Vidro", "Hidamari ga Kikoeru",
        "The Trainee", "His Man 3", "Spaceless", "The Rebound", "SunsetxVibes",
        "Under the Oak Tree", "Your Sky", "Cityboy_Log", "Egoist", "Inverse Identity",
        "The Eighth Sense", "30-sai made Dotei Da to Mahotsukai ni Nareru rashii", "Wandee Goodday",
        "Blue Boys", "A Man Who Defies the World of BL", "My Stand In", "At 25:00 in Akasaka",
        "Living with Him", "The Next Prince", "We Are", "Gray Shelter", "Boys Be Brave",
        "TharnType", "Two Worlds", "City of Stars", "Kiseki Chapter 2", "Deep Night",
        "Love Is like a Cat", "Jazz for Two", "Love isBetter the Second Time Around", "Bed Friend",
        "Taikan Yoho", "Old Fashion Cupcake", "To Be Continued", "Kieta Hatsukoi", "Cutie Pie",
        "Mr. Heart", "A Secretly Love", "My Strawberry Film", "Love Sea", "My Sweet Dear",
        "1000 Years Old", "Unknown", "Happy Ending", "Although I Love You and You?", "After Sundown",
        "Perfect Propose", "Anti Reset", "About Youth", "My Love Mix-Up!", "Love for Love's Sake",
        "Last Twilight", "Dead Friend Forever - DFF", "Night Dream", "Playboyy",
        "Behind the Shadows", "Your Name Engraved Herein", "A Breeze of Love", "Pit Babe",
        "Shadow", "Wuju Bakery", "Cherry Magic", "My Dear Gangster Oppa", "Bump Up Business",
        "If It's With You", "Absolute Zero", "Dear Ex", "Crazy Handsome Rich", "My Universe",
        "Only Friends", "Red, White & Royal Blue", "Marry My Dead Body", "Sing My Crush",
        "Jun & Jun", "Love Tractor", "Star Struck", "Love Mate", "The Director Who Buys Me Dinner",
        "Happy Merry Ending", "All the Liquors", "Our Dating Sim", "Unintentional Love Story",
        "A Shoulder to Cry On", "Choco Milk Shake", "His Man", "Merry Queer", "Love Class",
        "Ocean Likes Me", "Blueming", "Private Lessons", "Blue of Winter",
        "Cherry Blossoms After Winter", "Behind Cut", "Color Rush 2", "Color Rush",
        "First Love Again", "To My Star", "Semantic Error", "Tinted With You",
        "Kissable Lips", "Peach of Time", "Light On Me"
    )
}
